# Generated by Django 3.1.4 on 2021-02-07 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libapp', '0002_auto_20210204_0634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.ManyToManyField(related_name='books', to='libapp.Category'),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=256, verbose_name='ISBN'),
        ),
        migrations.CreateModel(
            name='BookSaleRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=256)),
                ('sale_date', models.DateTimeField(auto_now_add=True)),
                ('copy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sold', to='libapp.copy')),
            ],
        ),
    ]
